# Generated by Django 4.2.16 on 2024-10-31 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': [('visualizar_catalogo', 'puede ver lista de vehiciulos')]},
        ),
    ]
